---
interfaces:
    - name: Loopback0
      ip_address: 172.255.255.2 255.255.255.255
    - name: FastEthernet0/0.500
      ip_address: 10.1.1.2 255.255.255.252
      vlan: 500
    - name: FastEthernet0/0.501
      ip_address: 10.1.1.5 255.255.255.252
      vlan: 501
as_number: 62222
peer:
    - hostname: R1
      ip: 10.1.1.1
    - hostname: R3
      ip: 10.1.1.6
